Exersices 1
Andkleven/INF200-2019-Exersices pull request #4
Opened 2019-09-16 16:48 UTC by Andkleven

Have done every task on exercise 1

2019-09-23 17:27 UTC, danielambrosius requested changes
Code looks all right except the letter frequencies (see comment). And i would try to not have overly explicit function/variable names.

Unfortunately your code fails PEP8 (see below), so i cannot approve it. You should be fully able to catch this in pycharm looking at the check-mark in the upper right corner before you submit the code.

I would like you to address the PEP8 violations before merging.
EDIT: I have noticed that the acceptance criteria might not have been entirely clear regarding PEP8, so please don't close this pull request until **this thursday**, when Yngve, the other TA's and me have talked it over.

2019-09-23 17:27 UTC, danielambrosius commented on src/anders_mathiesen_ex/ex01/comp_to_loop.py
> +print(squares_by_loop(5))
Avoid print statements outside the main section of the program.

2019-09-23 17:27 UTC, danielambrosius commented on src/anders_mathiesen_ex/ex01/deck_by_comp.py
> +        print('ERROR!')
no blank line at end of file (PEP8 violation)

2019-09-23 17:27 UTC, danielambrosius commented on src/anders_mathiesen_ex/ex01/letter_counts.py
> +        print('{:3}{:10}'.format(letter, count))
no blank line at end of file (PEP8 violation)

2019-09-23 17:27 UTC, danielambrosius commented on src/anders_mathiesen_ex/ex01/letter_counts.py
> +    for symbol in list(txt):
this is not case-insensitive, i.e. 
`In [2]: letter_freq("HHhhhh")                                                      
Out[2]: {'H': 2, 'h': 4}`

2019-09-23 17:27 UTC, danielambrosius commented on src/anders_mathiesen_ex/ex01/tidy_code.py
> +def get_guess_bigger_then_or_lik_1():
please write all code in english. Also i think this function definition is a bit too explicit. could be something like `user_guess()`

2019-09-23 17:27 UTC, danielambrosius commented on src/anders_mathiesen_ex/ex01/tidy_code.py
> +        except:
This is pretty cool, though be wary of using a "bare" except statement as it is usually supposed to catch errors. A better option in this case would be an if-test.

2019-09-23 17:27 UTC, danielambrosius commented on src/anders_mathiesen_ex/ex01/tidy_code.py
> +def get_random_number():
roll_dice()?

2019-09-23 17:27 UTC, danielambrosius commented on src/anders_mathiesen_ex/ex01/tidy_code.py
> +def check_if_guess_is_correct(random_number, guess):
conventions is to write func names that return booleans as a "questions". i.e. just is_correct. In this case though, `is_equal()` would be much better, as that is what the function does irrespective of the rest of the script.

2019-09-25 18:02 UTC, danielambrosius commented
Hey!
Unfortunately your hand-in still won't pass. PEP8 quality control has been informed about in [this youtube video](https://www.youtube.com/watch?v=AyINGuxFpnU), and  the task discritpion:

> Check that your code passes the “quality control” in PyCharm!

Be sure to read through the task description before handing in the code as it sucks to fail on formalities.

2019-09-29 18:47 UTC, Andkleven commented
d

2019-09-29 18:47 UTC, merged